POST http://localhost:3000/user/create
Content-Type: application/json; charset=utf8
{
  "name": "Tony Delas",
  "email": "reidelas@gmail.com"
}

###
GET http://localhost:3000/user/findall

###
GET http://localhost:3000/user/update/:id

###
DELETE http://localhost:3000/user/delete/:id

###
GET http://localhost:3000/user/:id